<a href="https://colab.research.google.com/github/httplups/Curso-ML/blob/master/notebooks/3-lfb-split-data_ratings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
cd /content/drive/Shareddrives/Filmes Pra TI - Machine Learning

/content/drive/Shareddrives/Filmes Pra TI - Machine Learning


In [6]:
import pandas as pd
import numpy as np
import time
import datetime

all paths are related to drive folder

In [7]:
data_dir = 'data/processed/'

In [8]:
rating_df = pd.read_csv(data_dir + 'rating.csv')
rating_df.head()

userId  movieId  rating            timestamp  Liked  timestamp2
0       1        2     3.5  2005-04-02 23:53:47      1  1112486027
1       1       29     3.5  2005-04-02 23:31:16      1  1112484676
2       1       32     3.5  2005-04-02 23:33:39      1  1112484819
3       1       47     3.5  2005-04-02 23:32:07      1  1112484727
4       1       50     3.5  2005-04-02 23:29:40      1  1112484580

In [9]:
from sklearn.model_selection import train_test_split

In [ ]:
def datetime_to_timestamp(s):
    return int(time.mktime(datetime.datetime.strptime(s, '%Y-%m-%d %H:%M:%S').timetuple()))

In [ ]:
rating_df['timestamp2'] = rating_df.timestamp.apply(datetime_to_timestamp)

In [11]:
rating_df = rating_df.sort_values(by='timestamp2')

In [12]:
rating_df.to_csv(data_dir + 'rating.csv', index=False)

Split data into train, val and test sets

In [16]:
users = rating_df.userId.unique()
users.sort()
users

array([     1,      2,      3, ..., 138491, 138492, 138493])

In [21]:
Dataframe_Pandas = pd.DataFrame(data=[[0,1], [2,3], [4,5]], columns = ['First Column', 'Second Column'])
Dataframe_Numpy = Dataframe_Pandas.to_numpy()
Column_Index_Dictionary = dict(zip(Dataframe_Pandas.columns, 
list(range(0,len(Dataframe_Pandas.columns)))))

In [22]:
Dataframe_Pandas

First Column  Second Column
0             0              1
1             2              3
2             4              5

In [23]:
Dataframe_Numpy

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
Column_Index_Dictionary

{'First Column': 0, 'Second Column': 1}

In [26]:
Dataframe_Numpy[0, Column_Index_Dictionary['Second Column']] = 9
Dataframe_Numpy

array([[0, 9],
       [2, 3],
       [4, 5]])

In [28]:
for i, user in enumerate(users):
    # ratings of one user sorted by timestamp2
    group = rating_df[rating_df.userId == user]
    train, test = train_test_split(group, test_size=0.3, shuffle=False)
    val, test = train_test_split(test, test_size=0.5, shuffle=False)

    if i == 0:
        test.to_csv(data_dir + 'test_rating.csv', index=False)
        train.to_csv(data_dir + 'train_rating.csv', index=False)
        val.to_csv(data_dir + 'val_rating.csv', index=False)
    else:
        # append to existing csv file
        test.to_csv(data_dir + 'test_rating.csv', index=False, header=False, mode='a')
        train.to_csv(data_dir + 'train_rating.csv', index=False, header=False, mode='a')
        val.to_csv(data_dir + 'val_rating.csv',  index=False, header=False, mode='a')

    if (i % 1000) == 0:
        print(user)

1
1001
2001
3001
4001
5001
6001
7001
8001
9001
10001
11001
12001
13001
14001
15001
16001
17001
18001
19001
20001
21001
22001
23001
24001
25001
26001
27001
28001
29001
30001
31001
32001
33001
34001
35001
36001
37001
38001
39001
40001
41001
42001
43001
44001
45001
46001
47001
48001
49001
50001
51001
52001
53001
54001
55001
56001
57001
58001
59001
60001
61001
62001
63001
64001
65001
66001
67001
68001
69001
70001
71001
72001
73001
74001
75001
76001
77001
78001
79001
80001
81001
82001
83001
84001
85001
86001
87001
88001
89001
90001
91001
92001
93001
94001
95001
96001
97001
98001
99001
100001
101001
102001
103001
104001
105001
106001
107001
108001
109001
110001
111001
112001
113001
114001
115001
116001
117001
118001
119001
120001
121001
122001
123001
124001
125001
126001
127001
128001
129001
130001
131001
132001
133001
134001
135001
136001
137001
138001


In [30]:
train = pd.read_csv(data_dir + 'train_rating.csv')
val = pd.read_csv(data_dir + 'val_rating.csv')
test = pd.read_csv(data_dir + 'test_rating.csv')

In [35]:
train.shape

(13939850, 6)

In [36]:
val.shape

(2995066, 6)

In [37]:
test.shape

(3065347, 6)

In [34]:
train.drop_duplicates(inplace=True)
val.drop_duplicates(inplace=True)
test.drop_duplicates(inplace=True)